-- Generated by npm run db:bundle. Do not edit; migrations are authoritative.
-- Run as the database owner in Supabase SQL Editor. No accounts or secret keys are seeded.
begin;
select pg_advisory_xact_lock(871920);
create table if not exists public.schema_migrations(name text primary key,checksum text not null,applied_at timestamptz not null default now());
alter table public.schema_migrations enable row level security;
revoke all on public.schema_migrations from public,anon,authenticated;
grant all on public.schema_migrations to service_role;

-- 202610060001_core.sql
do $j1d_apply$
declare previous text;
begin
  select checksum into previous from public.schema_migrations where name='202610060001_core.sql';
  if found then
    if previous <> '8b36e8b7a55b1242e75f91a35d6b5f4b1d7da06076692c8708c0ae5fcd3c1887' then
      raise exception 'Applied migration checksum mismatch: 202610060001_core.sql';
    end if;
  else
    execute $j1d_source$-- Initial schema. Apply transactionally using the migration runner.
create type public.account_status as enum ('REGISTERED','EMAIL_VERIFIED','PROFILE_STARTED','PROFILE_COMPLETED','PHOTO_ADDED','VERIFICATION_PENDING','VERIFIED','ACTIVE','SUSPENDED','BANNED','DEACTIVATED','DELETION_PENDING','DELETED');
create table public.app_settings(id uuid primary key default gen_random_uuid(), key text unique not null, value jsonb not null, updated_at timestamptz not null default now());
create table public.feature_flags(id uuid primary key default gen_random_uuid(), key text unique not null, enabled boolean not null default false, rollout_percent int not null default 0 check(rollout_percent between 0 and 100), updated_at timestamptz not null default now());
create table public.users(id uuid primary key references auth.users(id) on delete cascade, date_of_birth date not null check(date_of_birth > date '1900-01-01'), status public.account_status not null default 'REGISTERED', is_test boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.relationship_goals(id uuid primary key default gen_random_uuid(), code text unique not null, name text not null);
create table public.interests(id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, active boolean not null default true);
create table public.profiles(user_id uuid primary key references public.users(id) on delete cascade, display_name text not null default '', gender text not null default '' check(gender in ('','woman','man','nonbinary','self_described')), city text not null default '', bio text not null default '' check(length(bio)<=1000), profession text not null default '', education text not null default '', goal text references public.relationship_goals(code), values text[] not null default '{}', communication text not null default '', personality text[] not null default '{}', visible boolean not null default true, paused boolean not null default false, show_online boolean not null default false, completion int not null default 0 check(completion between 0 and 100), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_preferences(user_id uuid primary key references public.users(id) on delete cascade, age_min int not null default 18 check(age_min>=18), age_max int not null default 60 check(age_max<=100), genders text[] not null default '{woman,man,nonbinary,self_described}', goals text[] not null default '{}', distance_km int not null default 100 check(distance_km between 1 and 500), deal_breakers jsonb not null default '{}', updated_at timestamptz not null default now(), check(age_min<=age_max));
create table public.user_locations(user_id uuid primary key references public.users(id) on delete cascade, latitude numeric(5,2) check(latitude between -90 and 90), longitude numeric(5,2) check(longitude between -180 and 180), city text not null, consent_at timestamptz, updated_at timestamptz not null default now(), check((latitude is null)=(longitude is null)));
create table public.profile_photos(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, storage_key text unique not null, position int not null check(position between 0 and 5), moderation_status text not null default 'pending' check(moderation_status in ('pending','approved','rejected')), mime text not null check(mime in ('image/jpeg','image/png','image/webp')), size_bytes int not null check(size_bytes between 1 and 5242880), created_at timestamptz not null default now(), unique(user_id,position));
create table public.profile_prompts(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, question text not null check(length(question) between 5 and 150), answer text not null check(length(answer) between 5 and 500), position int not null check(position between 0 and 2), unique(user_id,position));
create table public.profile_interests(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, interest_id uuid not null references public.interests(id), unique(user_id,interest_id));
create table public.education(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, institution text not null, qualification text, visible boolean not null default true, created_at timestamptz not null default now());
create table public.employment(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, profession text not null, company text, visible boolean not null default true, created_at timestamptz not null default now());
create table public.lifestyle_preferences(user_id uuid primary key references public.users(id) on delete cascade, preferences jsonb not null default '{}', updated_at timestamptz not null default now());
create table public.likes(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, target_id uuid not null references public.users(id) on delete cascade, kind text not null default 'like' check(kind in ('like','super_like')), operation_id uuid unique not null, created_at timestamptz not null default now(), unique(user_id,target_id), check(user_id<>target_id));
create table public.passes(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, target_id uuid not null references public.users(id) on delete cascade, operation_id uuid unique not null, created_at timestamptz not null default now(), unique(user_id,target_id), check(user_id<>target_id));
create table public.super_likes(id uuid primary key default gen_random_uuid(), like_id uuid unique not null references public.likes(id) on delete cascade, user_id uuid not null references public.users(id) on delete cascade, created_at timestamptz not null default now());
create table public.matches(id uuid primary key default gen_random_uuid(), user_a uuid not null references public.users(id) on delete cascade, user_b uuid not null references public.users(id) on delete cascade, created_at timestamptz not null default now(), ended_at timestamptz, unique(user_a,user_b), check(user_a<user_b));
create table public.match_preferences(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, match_id uuid not null references public.matches(id) on delete cascade, muted boolean not null default false, unique(user_id,match_id));
create table public.conversations(id uuid primary key default gen_random_uuid(), match_id uuid unique not null references public.matches(id) on delete cascade, created_at timestamptz not null default now());
create table public.conversation_members(id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.conversations(id) on delete cascade, user_id uuid not null references public.users(id) on delete cascade, last_read_at timestamptz, unique(conversation_id,user_id));
create table public.messages(id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.conversations(id) on delete cascade, sender_id uuid not null references public.users(id) on delete cascade, body text check(length(body) between 1 and 2000), kind text not null default 'text' check(kind in ('text','image','voice','gif')), media_key text, reply_to uuid references public.messages(id) on delete set null, client_id uuid not null, created_at timestamptz not null default now(), deleted_at timestamptz, unique(sender_id,client_id), check(body is not null or deleted_at is not null or media_key is not null));
create table public.message_reactions(id uuid primary key default gen_random_uuid(), message_id uuid not null references public.messages(id) on delete cascade, user_id uuid not null references public.users(id) on delete cascade, emoji text not null check(length(emoji)<=16), created_at timestamptz not null default now(), unique(message_id,user_id));
create table public.blocks(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, target_id uuid not null references public.users(id) on delete cascade, created_at timestamptz not null default now(), unique(user_id,target_id), check(user_id<>target_id));
create table public.reports(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, target_id uuid not null references public.users(id) on delete cascade, category text not null check(category in ('fake_profile','scam','harassment','threats','hate','sexual_misconduct','underage','spam','other')), details text not null check(length(details) between 10 and 2000), status text not null default 'open' check(status in ('open','reviewing','resolved','dismissed')), created_at timestamptz not null default now(), check(user_id<>target_id));
create table public.message_reports(id uuid primary key default gen_random_uuid(), report_id uuid unique not null references public.reports(id) on delete cascade, message_id uuid not null references public.messages(id) on delete cascade);
create table public.notifications(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, kind text not null, title text not null, resource_id uuid, read_at timestamptz, created_at timestamptz not null default now());
create table public.notification_preferences(user_id uuid primary key references public.users(id) on delete cascade, push_enabled boolean not null default false, email_enabled boolean not null default false, likes_enabled boolean not null default true, messages_enabled boolean not null default true, updated_at timestamptz not null default now());
create table public.device_tokens(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, token text unique not null, platform text not null check(platform in ('ios','android')), updated_at timestamptz not null default now());
create table public.notification_outbox(id uuid primary key default gen_random_uuid(), notification_id uuid unique not null references public.notifications(id) on delete cascade, attempts int not null default 0, available_at timestamptz not null default now(), locked_at timestamptz, delivered_at timestamptz, last_error_code text);
create table public.subscription_plans(id uuid primary key default gen_random_uuid(), code text unique not null check(code in ('free','plus','premium')), name text not null, amount_minor bigint not null check(amount_minor>=0), currency text not null check(currency ~ '^[A-Z]{3}$'), period_days int not null check(period_days between 1 and 366), entitlements jsonb not null default '{}', purchasable boolean not null default false, provider_plan_code text, updated_at timestamptz not null default now());
create table public.payments(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id), plan_id uuid not null references public.subscription_plans(id), provider text not null default 'paystack', reference text unique not null, idempotency_key uuid not null, amount_minor bigint not null check(amount_minor>0), currency text not null, period_days int not null check(period_days>0), status text not null default 'initiated' check(status in ('initiated','pending','successful','failed','refunded')), checkout_url text, created_at timestamptz not null default now(), settled_at timestamptz, unique(user_id,idempotency_key));
create table public.subscriptions(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id), plan_id uuid not null references public.subscription_plans(id), payment_id uuid unique references public.payments(id), status text not null default 'active' check(status in ('active','expired','cancelled')), starts_at timestamptz not null, ends_at timestamptz not null, cancel_at_period_end boolean not null default false, provider_subscription_code text, created_at timestamptz not null default now(), check(ends_at>starts_at));
create table public.payment_events(id uuid primary key default gen_random_uuid(), provider text not null, event_key text not null, event_type text not null, payment_id uuid references public.payments(id), created_at timestamptz not null default now(), unique(provider,event_key));
create table public.verification_requests(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, method text not null check(method in ('selfie','photo','phone')), status text not null default 'pending' check(status in ('pending','approved','rejected')), created_at timestamptz not null default now(), reviewed_at timestamptz);
create table public.verification_results(id uuid primary key default gen_random_uuid(), request_id uuid unique not null references public.verification_requests(id) on delete cascade, result text not null, reviewer_id uuid references public.users(id), created_at timestamptz not null default now());
create table public.verification_documents(id uuid primary key default gen_random_uuid(), request_id uuid not null references public.verification_requests(id) on delete cascade, storage_key text unique not null, purge_at timestamptz not null, created_at timestamptz not null default now());
create table public.profile_verifications(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, method text not null check(method in ('email','phone','selfie','photo')), request_id uuid references public.verification_requests(id) on delete set null, verified_at timestamptz not null default now(), revoked_at timestamptz, unique(user_id,method));
create table public.emergency_contacts(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, name text not null, phone text not null, consent_confirmed boolean not null default false, created_at timestamptz not null default now());
create table public.date_plans(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, match_id uuid references public.matches(id) on delete set null, venue text not null, starts_at timestamptz not null, created_at timestamptz not null default now());
create table public.date_safety_sessions(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, person_name text not null, venue text not null, starts_at timestamptz not null, ends_at timestamptz not null, trusted_contact_id uuid references public.emergency_contacts(id) on delete set null, location_consent boolean not null default false, status text not null default 'scheduled' check(status in ('scheduled','active','ended','alert')), last_check_in_at timestamptz, ended_at timestamptz, created_at timestamptz not null default now(), check(ends_at>starts_at));
create table public.compatibility_factors(id uuid primary key default gen_random_uuid(), code text unique not null, weight numeric not null check(weight>=0), enabled boolean not null default true, updated_at timestamptz not null default now());
create table public.compatibility_scores(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, target_id uuid not null references public.users(id) on delete cascade, score numeric check(score between 0 and 100), factors jsonb not null, algorithm_version text not null, expires_at timestamptz not null, unique(user_id,target_id,algorithm_version));
create table public.ai_recommendations(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, kind text not null, output jsonb not null, model text not null, created_at timestamptz not null default now(), expires_at timestamptz not null);
create table public.profile_views(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, target_id uuid not null references public.users(id) on delete cascade, created_at timestamptz not null default now());
create table public.boosts(id uuid primary key default gen_random_uuid(), name text not null, duration_minutes int not null check(duration_minutes>0), exposure_multiplier numeric not null check(exposure_multiplier between 1 and 3), amount_minor bigint not null check(amount_minor>=0), currency text not null, enabled boolean not null default false);
create table public.user_boosts(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, boost_id uuid not null references public.boosts(id), purchase_id uuid unique references public.payments(id), boost_start timestamptz not null, boost_end timestamptz not null, impressions int not null default 0, profile_views int not null default 0, likes_received int not null default 0, matches_generated int not null default 0, check(boost_end>boost_start));
create table public.admin_users(user_id uuid primary key references public.users(id), role text not null check(role in ('SUPER_ADMIN','ADMIN','MODERATOR','SUPPORT','FINANCE','ANALYST')), active boolean not null default true, created_at timestamptz not null default now());
create table public.admin_actions(id uuid primary key default gen_random_uuid(), admin_id uuid not null references public.admin_users(user_id), action text not null, target_id uuid references public.users(id), reason text not null, created_at timestamptz not null default now());
create table public.moderation_queue(id uuid primary key default gen_random_uuid(), report_id uuid unique references public.reports(id), user_id uuid not null references public.users(id), resource_id uuid, kind text not null, risk_score int not null default 0 check(risk_score between 0 and 100), signals text[] not null default '{}', status text not null default 'pending' check(status in ('pending','reviewing','resolved')), created_at timestamptz not null default now());
create table public.moderation_actions(id uuid primary key default gen_random_uuid(), queue_id uuid references public.moderation_queue(id), admin_action_id uuid not null references public.admin_actions(id), created_at timestamptz not null default now());
create table public.audit_logs(id uuid primary key default gen_random_uuid(), actor_id uuid references public.users(id), action text not null, resource_id uuid, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.analytics_events(id uuid primary key default gen_random_uuid(), user_id uuid references public.users(id) on delete set null, event text not null, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.account_deletion_requests(id uuid primary key default gen_random_uuid(), user_id uuid unique not null references public.users(id), status text not null default 'pending' check(status in ('pending','processing','completed','failed')), requested_at timestamptz not null default now(), completed_at timestamptz);

-- Enable deny-by-default RLS and remove Supabase's permissive default grants.
do $$ declare t record; begin
 for t in select tablename from pg_tables where schemaname='public' and tablename<>'schema_migrations' loop
  execute format('alter table public.%I enable row level security',t.tablename);
  execute format('revoke all on public.%I from anon, authenticated',t.tablename);
  execute format('grant all on public.%I to service_role',t.tablename);
 end loop;
end $$;
grant usage on schema public to anon,authenticated,service_role;
do $$ declare t text; begin
 foreach t in array array['users','profiles','user_preferences','user_locations','profile_photos','profile_prompts','profile_interests','education','employment','lifestyle_preferences','likes','passes','super_likes','match_preferences','reports','notifications','notification_preferences','device_tokens','subscriptions','payments','verification_requests','profile_verifications','emergency_contacts','date_plans','date_safety_sessions','compatibility_scores','ai_recommendations','profile_views','user_boosts','account_deletion_requests'] loop
  execute format('grant select on public.%I to authenticated',t);
  execute format('create policy own_read on public.%I for select to authenticated using (%I=(select auth.uid()))',t,case when t='users' then 'id' else 'user_id' end);
 end loop;
 foreach t in array array['interests','relationship_goals','subscription_plans','compatibility_factors'] loop
  execute format('grant select on public.%I to anon,authenticated',t);
  execute format('create policy catalog_read on public.%I for select to anon,authenticated using(true)',t);
 end loop;
end $$;

-- Index each foreign-key column, plus composite indexes for bounded list reads.
do $$ declare c record; begin
 for c in select distinct t.relname,a.attname from pg_constraint f join pg_class t on t.oid=f.conrelid join pg_namespace n on n.oid=t.relnamespace join pg_attribute a on a.attrelid=t.oid and a.attnum=any(f.conkey) where f.contype='f' and n.nspname='public' loop
  execute format('create index if not exists %I on public.%I(%I)',left(c.relname||'_'||c.attname||'_fk_idx',63),c.relname,c.attname);
 end loop;
end $$;
create index messages_cursor_idx on public.messages(conversation_id,created_at desc,id desc);
create index notifications_cursor_idx on public.notifications(user_id,created_at desc,id desc);
create index likes_daily_idx on public.likes(user_id,created_at);
create index profiles_discover_idx on public.profiles(city,gender,user_id) where visible and not paused;
create index users_active_idx on public.users(id) where status='ACTIVE';
create index subscriptions_entitlement_idx on public.subscriptions(user_id,ends_at desc) where status='active';
create index notification_outbox_due_idx on public.notification_outbox(available_at) where delivered_at is null;
create index moderation_pending_idx on public.moderation_queue(created_at) where status='pending';

insert into public.app_settings(key,value) values ('minimum_age','18'),('matching_version','"v1"');
insert into public.relationship_goals(code,name) values ('serious','Serious relationship'),('marriage','Marriage'),('long_term','Long-term dating'),('dating','Dating'),('friendship','Friendship'),('exploring','Still figuring it out');
insert into public.interests(code,name) values ('travel','Travel'),('reading','Reading'),('music','Music'),('art','Art'),('cooking','Cooking'),('fitness','Fitness'),('technology','Technology'),('nature','Nature'),('film','Film'),('photography','Photography'),('volunteering','Volunteering'),('food','Food'),('dance','Dance'),('entrepreneurship','Entrepreneurship');
-- No invented live prices. Operator must configure and enable paid plans.
insert into public.subscription_plans(code,name,amount_minor,currency,period_days,entitlements) values
 ('free','Free',0,'NGN',30,'{"daily_likes":15,"super_likes":0,"see_likes":false,"ai":false,"advanced_filters":false}'),
 ('plus','Plus',0,'NGN',30,'{"daily_likes":100,"super_likes":3,"see_likes":true,"ai":false,"advanced_filters":true}'),
 ('premium','Premium',0,'NGN',30,'{"daily_likes":100000,"super_likes":10,"see_likes":true,"ai":true,"advanced_filters":true}');
insert into public.compatibility_factors(code,weight) values ('goals',25),('values',15),('lifestyle',15),('interests',10),('communication',10),('personality',10),('preferences',10),('distance',5);
insert into public.feature_flags(key) values ('ai_matchmaker'),('video_calling'),('boosts'),('super_likes'),('verification'),('premium_filters'),('new_matching');

create function public.provision_user() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare dob date; minimum int;
begin
 minimum:=greatest(18,coalesce((select value::text::int from public.app_settings where key='minimum_age'),18));
 begin dob:=(new.raw_user_meta_data->>'date_of_birth')::date; exception when others then raise exception 'INVALID_DATE_OF_BIRTH'; end;
 if dob is null or dob>current_date-(minimum||' years')::interval or dob<current_date-interval '120 years' then raise exception 'AGE_REQUIREMENT'; end if;
 insert into public.users(id,date_of_birth,status) values(new.id,dob,case when new.email_confirmed_at is null then 'REGISTERED'::public.account_status else 'EMAIL_VERIFIED'::public.account_status end);
 insert into public.profiles(user_id) values(new.id);
 insert into public.user_preferences(user_id) values(new.id);
 insert into public.lifestyle_preferences(user_id) values(new.id);
 insert into public.notification_preferences(user_id) values(new.id);
 return new;
end $$;
create trigger provision_user after insert on auth.users for each row execute function public.provision_user();
create function public.sync_email_verification() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin
 if new.email_confirmed_at is not null and old.email_confirmed_at is null then
  update public.users set status='EMAIL_VERIFIED',updated_at=now() where id=new.id and status='REGISTERED';
  insert into public.profile_verifications(user_id,method) values(new.id,'email') on conflict do nothing;
 end if;
 return new;
end $$;
create trigger sync_email_verification after update of email_confirmed_at on auth.users for each row execute function public.sync_email_verification();
revoke all on all functions in schema public from public,anon,authenticated;
$j1d_source$;
    insert into public.schema_migrations(name,checksum) values('202610060001_core.sql','8b36e8b7a55b1242e75f91a35d6b5f4b1d7da06076692c8708c0ae5fcd3c1887');
  end if;
end
$j1d_apply$;

-- 202610060002_workflows.sql
do $j1d_apply$
declare previous text;
begin
  select checksum into previous from public.schema_migrations where name='202610060002_workflows.sql';
  if found then
    if previous <> 'afa18aa377c4477ae7905d6965ea65c5cca242ef3da2d638066a6a0082e13116' then
      raise exception 'Applied migration checksum mismatch: 202610060002_workflows.sql';
    end if;
  else
    execute $j1d_source$-- Narrow functions are the sole client write path; all authorization is repeated here.
create function public.require_actor(active_required boolean default false) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=auth.uid(); s public.account_status;
begin
 select status into s from public.users where id=actor;
 if actor is null or s is null or s in ('SUSPENDED','BANNED','DELETION_PENDING','DELETED','DEACTIVATED') then raise exception 'ACCOUNT_UNAVAILABLE'; end if;
 if active_required and s<>'ACTIVE' then raise exception 'ONBOARDING_REQUIRED'; end if;
 return actor;
end $$;
create function public.is_blocked(a uuid,b uuid) returns boolean language sql stable security definer set search_path=public,pg_temp as $$select exists(select 1 from public.blocks where (user_id=a and target_id=b) or (user_id=b and target_id=a))$$;
create function public.can_chat(c uuid,actor uuid) returns boolean language sql stable security definer set search_path=public,pg_temp as $$
 select exists(select 1 from public.conversations x join public.matches m on m.id=x.match_id join public.users a on a.id=m.user_a join public.users b on b.id=m.user_b where x.id=c and m.ended_at is null and actor in(m.user_a,m.user_b) and a.status='ACTIVE' and b.status='ACTIVE' and not public.is_blocked(m.user_a,m.user_b))
$$;
create function public.entitlements(actor uuid) returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
 select coalesce((select p.entitlements from public.subscriptions s join public.subscription_plans p on p.id=s.plan_id where s.user_id=actor and s.status='active' and s.starts_at<=now() and s.ends_at>now() order by (p.entitlements->>'daily_likes')::int desc limit 1),(select entitlements from public.subscription_plans where code='free'))
$$;
create function public.profile_projection(target uuid) returns jsonb language sql stable security definer set search_path=public,pg_temp as $$
 select jsonb_build_object('user_id',p.user_id,'display_name',p.display_name,'age',extract(year from age(u.date_of_birth))::int,'gender',p.gender,'city',p.city,'bio',p.bio,'profession',p.profession,'education',p.education,'goal',p.goal,'values',p.values,'communication',p.communication,'personality',p.personality,'lifestyle',coalesce(l.preferences,'{}'::jsonb),'interests',coalesce((select jsonb_agg(i.code order by i.code) from public.profile_interests pi join public.interests i on i.id=pi.interest_id where pi.user_id=p.user_id),'[]'::jsonb),'prompts',coalesce((select jsonb_agg(jsonb_build_object('question',question,'answer',answer) order by position) from public.profile_prompts where user_id=p.user_id),'[]'::jsonb),'photo_keys',coalesce((select jsonb_agg(storage_key order by position) from public.profile_photos where user_id=p.user_id and moderation_status='approved'),'[]'::jsonb),'verified',exists(select 1 from public.profile_verifications v where v.user_id=p.user_id and v.method='selfie' and v.revoked_at is null)) from public.profiles p join public.users u on u.id=p.user_id left join public.lifestyle_preferences l on l.user_id=p.user_id where p.user_id=target
$$;
create function public.distance_between(a uuid,b uuid) returns numeric language sql stable security definer set search_path=public,pg_temp as $$
 select (6371*2*asin(sqrt(least(1,power(sin(radians((y.latitude-x.latitude)::float8)/2),2)+cos(radians(x.latitude::float8))*cos(radians(y.latitude::float8))*power(sin(radians((y.longitude-x.longitude)::float8)/2),2)))))::numeric from public.user_locations x join public.user_locations y on y.user_id=b where x.user_id=a and x.consent_at is not null and y.consent_at is not null
$$;
create function public.eligible_pair(a uuid,b uuid) returns boolean language sql stable security definer set search_path=public,pg_temp as $$
 select exists(select 1 from public.users ua join public.profiles pa on pa.user_id=ua.id join public.user_preferences xa on xa.user_id=ua.id join public.users ub on ub.id=b join public.profiles pb on pb.user_id=ub.id join public.user_preferences xb on xb.user_id=ub.id where ua.id=a and a<>b and ua.status='ACTIVE' and ub.status='ACTIVE' and pb.visible and not pb.paused and pa.visible and not pa.paused and not public.is_blocked(a,b) and extract(year from age(ub.date_of_birth)) between xa.age_min and xa.age_max and extract(year from age(ua.date_of_birth)) between xb.age_min and xb.age_max and pb.gender=any(xa.genders) and pa.gender=any(xb.genders) and (cardinality(xa.goals)=0 or pb.goal=any(xa.goals)) and (cardinality(xb.goals)=0 or pa.goal=any(xb.goals)) and coalesce(public.distance_between(a,b)<=least(xa.distance_km,xb.distance_km),lower(pa.city)=lower(pb.city)) and not exists(select 1 from jsonb_each_text(xa.deal_breakers) d where (select preferences->>d.key from public.lifestyle_preferences where user_id=b) is distinct from d.value) and not exists(select 1 from jsonb_each_text(xb.deal_breakers) d where (select preferences->>d.key from public.lifestyle_preferences where user_id=a) is distinct from d.value))
$$;
create function public.rpc_me() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor();
begin return public.profile_projection(actor)||jsonb_build_object('status',(select status from public.users where id=actor),'date_of_birth',(select date_of_birth from public.users where id=actor),'visible',(select visible from public.profiles where user_id=actor),'paused',(select paused from public.profiles where user_id=actor),'show_online',(select show_online from public.profiles where user_id=actor),'completion',(select completion from public.profiles where user_id=actor),'preferences',(select to_jsonb(p)-'user_id' from public.user_preferences p where user_id=actor),'photo_review',coalesce((select jsonb_agg(jsonb_build_object('id',id,'position',position,'status',moderation_status)) from public.profile_photos where user_id=actor),'[]'::jsonb),'entitlements',public.entitlements(actor)); end $$;
create function public.rpc_save_profile(payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(); count_interests int; done int; has_photo boolean;
begin
 if length(payload->>'display_name') not between 2 and 50 or length(payload->>'bio') not between 20 and 1000 or length(payload->>'city') not between 2 and 100 or jsonb_array_length(payload->'interests') not between 3 and 20 or jsonb_array_length(payload->'prompts')>3 then raise exception 'INVALID_PROFILE'; end if;
 select count(distinct i.code) into count_interests from public.interests i where active and code in (select jsonb_array_elements_text(payload->'interests'));
 if count_interests<>jsonb_array_length(payload->'interests') then raise exception 'INVALID_INTERESTS'; end if;
 update public.profiles set display_name=payload->>'display_name',gender=payload->>'gender',city=payload->>'city',bio=payload->>'bio',profession=left(payload->>'profession',100),education=left(payload->>'education',100),goal=payload->>'goal',values=array(select jsonb_array_elements_text(payload->'values')),communication=left(payload->>'communication',50),personality=array(select jsonb_array_elements_text(payload->'personality')),updated_at=now() where user_id=actor;
 update public.lifestyle_preferences set preferences=payload->'lifestyle',updated_at=now() where user_id=actor;
 delete from public.profile_interests where user_id=actor;
 insert into public.profile_interests(user_id,interest_id) select actor,id from public.interests where code in(select jsonb_array_elements_text(payload->'interests'));
 delete from public.profile_prompts where user_id=actor;
 insert into public.profile_prompts(user_id,question,answer,position) select actor,item->>'question',item->>'answer',(ord-1)::int from jsonb_array_elements(payload->'prompts') with ordinality as t(item,ord);
 has_photo:=exists(select 1 from public.profile_photos where user_id=actor and moderation_status='approved');
 done:=case when has_photo then 100 else 88 end;
 update public.profiles set completion=done where user_id=actor;
 update public.users set status=case when has_photo and exists(select 1 from auth.users where id=actor and email_confirmed_at is not null) then 'ACTIVE'::public.account_status else 'PROFILE_COMPLETED'::public.account_status end,updated_at=now() where id=actor;
 insert into public.analytics_events(user_id,event) values(actor,'profile_completed');
 return public.rpc_me();
end $$;
create function public.rpc_preferences(payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor();
begin
 if jsonb_array_length(payload->'genders') not between 1 and 4 or not (payload->'genders') <@ '["woman","man","nonbinary","self_described"]'::jsonb then raise exception 'INVALID_PREFERENCES'; end if;
 if coalesce((public.entitlements(actor)->>'advanced_filters')::boolean,false)=false and payload->'deal_breakers'<>'{}'::jsonb then raise exception 'PREMIUM_REQUIRED'; end if;
 update public.user_preferences set age_min=(payload->>'age_min')::int,age_max=(payload->>'age_max')::int,genders=array(select jsonb_array_elements_text(payload->'genders')),goals=array(select jsonb_array_elements_text(payload->'goals')),distance_km=(payload->>'distance_km')::int,deal_breakers=payload->'deal_breakers',updated_at=now() where user_id=actor;
 return public.rpc_me();
end $$;
create function public.rpc_discover(after_id uuid default null,page_size int default 20) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(true); result jsonb;
begin
 select coalesce(jsonb_agg(public.profile_projection(p.user_id)||jsonb_build_object('distance_km',case when public.distance_between(actor,p.user_id) is null then null else ceil(public.distance_between(actor,p.user_id)/5)*5 end) order by p.user_id),'[]'::jsonb) into result from (select user_id from public.profiles where (after_id is null or user_id>after_id) and public.eligible_pair(actor,user_id) and not exists(select 1 from public.likes where user_id=actor and target_id=profiles.user_id) and not exists(select 1 from public.passes where user_id=actor and target_id=profiles.user_id) order by user_id limit greatest(1,least(page_size,30))) p;
 return result;
end $$;
create function public.rpc_profile(target uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(true);
begin
 if target<>actor and (public.is_blocked(actor,target) or not (public.eligible_pair(actor,target) or exists(select 1 from public.matches m join public.users u on u.id=target where u.status='ACTIVE' and ended_at is null and actor in(user_a,user_b) and target in(user_a,user_b)))) then raise exception 'PROFILE_UNAVAILABLE'; end if;
 return public.profile_projection(target);
end $$;
create function public.notify(target uuid,kind text,title text,resource uuid) returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare n uuid;
begin insert into public.notifications(user_id,kind,title,resource_id) values(target,kind,title,resource) returning id into n;insert into public.notification_outbox(notification_id) values(n);end $$;
create function public.rpc_interact(target uuid,operation uuid,action text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(true); mid uuid; cid uuid; existing record; quota int; used int;
begin
 if target=actor or action not in('like','super_like','pass') then raise exception 'INVALID_INTERACTION'; end if;
 perform pg_advisory_xact_lock(hashtextextended(actor::text,11));
 perform pg_advisory_xact_lock(hashtextextended(least(actor,target)::text||greatest(actor,target)::text,12));
 if not public.eligible_pair(actor,target) then raise exception 'PROFILE_UNAVAILABLE'; end if;
 select * into existing from public.likes where operation_id=operation;
 if found and (existing.user_id<>actor or existing.target_id<>target or existing.kind<>action) then raise exception 'IDEMPOTENCY_CONFLICT'; end if;
 if not found and exists(select 1 from public.passes where operation_id=operation and (user_id<>actor or target_id<>target or action<>'pass')) then raise exception 'IDEMPOTENCY_CONFLICT'; end if;
 if action='pass' then
  if exists(select 1 from public.likes where operation_id=operation) then raise exception 'IDEMPOTENCY_CONFLICT'; end if;
  insert into public.passes(user_id,target_id,operation_id) values(actor,target,operation) on conflict(user_id,target_id) do nothing;
  return jsonb_build_object('matched',false);
 end if;
 if exists(select 1 from public.passes where operation_id=operation) then raise exception 'IDEMPOTENCY_CONFLICT'; end if;
 if not exists(select 1 from public.likes where user_id=actor and target_id=target) then
  quota:=(public.entitlements(actor)->>'daily_likes')::int;
  select count(*) into used from public.likes where user_id=actor and created_at>=date_trunc('day',now());
  if used>=quota then raise exception 'DAILY_LIMIT'; end if;
  if action='super_like' then
   if not exists(select 1 from public.feature_flags where key='super_likes' and enabled) then raise exception 'FEATURE_UNAVAILABLE'; end if;
   quota:=coalesce((public.entitlements(actor)->>'super_likes')::int,0);
   select count(*) into used from public.super_likes where user_id=actor and created_at>=date_trunc('day',now());
   if used>=quota then raise exception 'PREMIUM_REQUIRED'; end if;
  end if;
  insert into public.likes(user_id,target_id,kind,operation_id) values(actor,target,action,operation);
  if action='super_like' then insert into public.super_likes(like_id,user_id) select id,actor from public.likes where operation_id=operation; end if;
  insert into public.analytics_events(user_id,event) values(actor,case when action='super_like' then 'super_like_sent' else 'profile_liked' end);
 end if;
 if exists(select 1 from public.likes where user_id=target and target_id=actor) then
  insert into public.matches(user_a,user_b) values(least(actor,target),greatest(actor,target)) on conflict(user_a,user_b) do nothing returning id into mid;
  if mid is not null then
   insert into public.conversations(match_id) values(mid) returning id into cid;
   insert into public.conversation_members(conversation_id,user_id) values(cid,actor),(cid,target);
   perform public.notify(actor,'match','A connection worth exploring',mid);perform public.notify(target,'match','A connection worth exploring',mid);
   insert into public.analytics_events(user_id,event,metadata) values(actor,'match_created',jsonb_build_object('match_id',mid));
  else select id into mid from public.matches where user_a=least(actor,target) and user_b=greatest(actor,target) and ended_at is null;select id into cid from public.conversations where match_id=mid;end if;
 end if;
 return jsonb_build_object('matched',mid is not null,'match_id',mid,'conversation_id',cid);
end $$;
create function public.rpc_matches() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(true);
begin return coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'conversation_id',c.id,'created_at',m.created_at,'profile',public.profile_projection(case when m.user_a=actor then m.user_b else m.user_a end)) order by m.created_at desc) from public.matches m join public.conversations c on c.match_id=m.id where public.can_chat(c.id,actor)),'[]'::jsonb);end $$;
create function public.rpc_incoming_likes() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(true);
begin if not coalesce((public.entitlements(actor)->>'see_likes')::boolean,false) then raise exception 'PREMIUM_REQUIRED';end if;return coalesce((select jsonb_agg(public.profile_projection(x.user_id)) from (select user_id from public.likes where target_id=actor and public.eligible_pair(actor,user_id) order by created_at desc limit 50)x),'[]'::jsonb);end $$;
create function public.rpc_block(target uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor();
begin if target=actor then raise exception 'INVALID_TARGET';end if;perform pg_advisory_xact_lock(hashtextextended(least(actor,target)::text||greatest(actor,target)::text,12));insert into public.blocks(user_id,target_id) values(actor,target) on conflict do nothing;update public.matches set ended_at=now() where user_a=least(actor,target) and user_b=greatest(actor,target) and ended_at is null;insert into public.audit_logs(actor_id,action,resource_id) values(actor,'block_created',target);return '{"blocked":true}'::jsonb;end $$;
create function public.rpc_unmatch(mid uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(); m record;
begin select * into m from public.matches where id=mid and actor in(user_a,user_b);if not found then raise exception 'MATCH_UNAVAILABLE';end if;perform pg_advisory_xact_lock(hashtextextended(m.user_a::text||m.user_b::text,12));update public.matches set ended_at=coalesce(ended_at,now()) where id=mid;delete from public.likes where (user_id=m.user_a and target_id=m.user_b) or (user_id=m.user_b and target_id=m.user_a);return '{"unmatched":true}'::jsonb;end $$;
create function public.rpc_messages(cid uuid,before_time timestamptz default null,before_id uuid default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(true);
begin if not public.can_chat(cid,actor) then raise exception 'CONVERSATION_UNAVAILABLE';end if;return coalesce((select jsonb_agg(to_jsonb(x) order by x.created_at desc,x.id desc) from (select id,conversation_id,sender_id,body,reply_to,client_id,created_at,deleted_at from public.messages where conversation_id=cid and (before_time is null or (created_at,id)<(before_time,before_id)) order by created_at desc,id desc limit 30)x),'[]'::jsonb);end $$;
create function public.rpc_send_message(cid uuid,payload jsonb,risk int default 0,signals text[] default '{}') returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(true); m record; result public.messages; recipient uuid;
begin
 select mm.* into m from public.conversations c join public.matches mm on mm.id=c.match_id where c.id=cid;
 if not found then raise exception 'CONVERSATION_UNAVAILABLE';end if;
 perform pg_advisory_xact_lock(hashtextextended(actor::text,13));perform pg_advisory_xact_lock(hashtextextended(m.user_a::text||m.user_b::text,12));
 if not public.can_chat(cid,actor) then raise exception 'CONVERSATION_UNAVAILABLE';end if;
 select * into result from public.messages where sender_id=actor and client_id=(payload->>'client_id')::uuid;
 if found then if result.conversation_id<>cid or result.body is distinct from payload->>'body' then raise exception 'IDEMPOTENCY_CONFLICT';end if;return to_jsonb(result);end if;
 if (select count(*) from public.messages where sender_id=actor and created_at>now()-interval '1 minute')>=30 then raise exception 'MESSAGE_LIMIT';end if;
 if payload->>'reply_to' is not null and not exists(select 1 from public.messages where id=(payload->>'reply_to')::uuid and conversation_id=cid and deleted_at is null) then raise exception 'INVALID_REPLY';end if;
 insert into public.messages(conversation_id,sender_id,body,client_id,reply_to) values(cid,actor,payload->>'body',(payload->>'client_id')::uuid,(payload->>'reply_to')::uuid) returning * into result;
 recipient:=case when m.user_a=actor then m.user_b else m.user_a end;
 perform public.notify(recipient,'message','You have a new message',cid);
 -- AI/rule signals only create review work; they never ban or suspend.
 if risk>=50 then insert into public.moderation_queue(user_id,resource_id,kind,risk_score,signals) values(actor,result.id,'message_signal',least(100,risk),signals);end if;
 insert into public.analytics_events(user_id,event) values(actor,'message_sent');
 return to_jsonb(result);
end $$;
create function public.rpc_message_action(mid uuid,action text,emoji_value text default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(true); m public.messages;
begin select * into m from public.messages where id=mid;if not found or not public.can_chat(m.conversation_id,actor) then raise exception 'MESSAGE_UNAVAILABLE';end if;
 if action='delete' then if m.sender_id<>actor then raise exception 'FORBIDDEN';end if;update public.messages set body=null,media_key=null,deleted_at=now() where id=mid;
 elsif action='react' then if emoji_value not in('❤️','👍','😊','😂','🎉') then raise exception 'INVALID_REACTION';end if;insert into public.message_reactions(message_id,user_id,emoji) values(mid,actor,emoji_value) on conflict(message_id,user_id) do update set emoji=excluded.emoji;
 else raise exception 'INVALID_ACTION';end if;return '{"updated":true}'::jsonb;end $$;
create function public.rpc_read_conversation(cid uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(true);
begin if not public.can_chat(cid,actor) then raise exception 'CONVERSATION_UNAVAILABLE';end if;update public.conversation_members set last_read_at=now() where conversation_id=cid and user_id=actor;return '{"read":true}'::jsonb;end $$;
create function public.rpc_report(payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(); target uuid:=(payload->>'target_id')::uuid; rid uuid; mid uuid:=(payload->>'message_id')::uuid;
begin
 if target=actor then raise exception 'INVALID_TARGET';end if;
 if (select count(*) from public.reports where user_id=actor and created_at>now()-interval '1 day')>=20 then raise exception 'REPORT_LIMIT';end if;
 if mid is not null and not exists(select 1 from public.messages m join public.conversation_members cm on cm.conversation_id=m.conversation_id where m.id=mid and m.sender_id=target and cm.user_id=actor) then raise exception 'MESSAGE_UNAVAILABLE';end if;
 insert into public.reports(user_id,target_id,category,details) values(actor,target,payload->>'category',payload->>'details') returning id into rid;
 if mid is not null then insert into public.message_reports(report_id,message_id) values(rid,mid);end if;
 insert into public.moderation_queue(report_id,user_id,resource_id,kind) values(rid,target,mid,'report');
 insert into public.analytics_events(user_id,event) values(actor,'report_created');return jsonb_build_object('id',rid,'status','open');
end $$;
create function public.rpc_privacy(payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor();
begin update public.profiles set visible=coalesce((payload->>'visible')::boolean,visible),paused=coalesce((payload->>'paused')::boolean,paused),show_online=coalesce((payload->>'show_online')::boolean,show_online),updated_at=now() where user_id=actor;return public.rpc_me();end $$;
create function public.rpc_deletion() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=auth.uid();
begin if actor is null then raise exception 'UNAUTHENTICATED';end if;insert into public.account_deletion_requests(user_id) values(actor) on conflict(user_id) do nothing;update public.users set status='DELETION_PENDING',updated_at=now() where id=actor;update public.profiles set visible=false,paused=true where user_id=actor;update public.matches set ended_at=coalesce(ended_at,now()) where actor in(user_a,user_b);delete from public.device_tokens where user_id=actor;insert into public.audit_logs(actor_id,action) values(actor,'account_deletion_requested');return '{"status":"pending","message":"Your profile is hidden and access revoked. Erasure is pending processing."}'::jsonb;end $$;
create function public.rpc_safety_create(payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(); result public.date_safety_sessions; contact uuid:=(payload->>'trusted_contact_id')::uuid;
begin if contact is not null and not exists(select 1 from public.emergency_contacts where id=contact and user_id=actor and consent_confirmed) then raise exception 'CONTACT_UNAVAILABLE';end if;if (payload->>'ends_at')::timestamptz>(payload->>'starts_at')::timestamptz+interval '24 hours' then raise exception 'INVALID_SESSION';end if;
 if (payload->>'location_consent')::boolean then raise exception 'LOCATION_SHARING_UNAVAILABLE';end if;
 insert into public.date_safety_sessions(user_id,person_name,venue,starts_at,ends_at,trusted_contact_id,location_consent) values(actor,payload->>'person_name',payload->>'venue',(payload->>'starts_at')::timestamptz,(payload->>'ends_at')::timestamptz,contact,false) returning * into result;return to_jsonb(result);end $$;
create function public.rpc_safety_action(sid uuid,action text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(); result public.date_safety_sessions;
begin if action not in('check_in','end','alert') then raise exception 'INVALID_ACTION';end if;if action='alert' then raise exception 'ALERT_DELIVERY_UNAVAILABLE';end if;update public.date_safety_sessions set status=case when action='end' then 'ended' else 'active' end,last_check_in_at=case when action='check_in' then now() else last_check_in_at end,ended_at=case when action='end' then now() else null end where id=sid and user_id=actor and status<>'ended' returning * into result;if not found then raise exception 'SESSION_UNAVAILABLE';end if;return to_jsonb(result);end $$;

-- Live membership is rechecked by RLS on every message read/realtime event.
grant select on public.matches,public.conversations,public.conversation_members,public.messages,public.message_reactions,public.blocks to authenticated;
create policy matches_read on public.matches for select to authenticated using(ended_at is null and auth.uid() in(user_a,user_b) and not public.is_blocked(user_a,user_b));
create policy conversations_read on public.conversations for select to authenticated using(public.can_chat(id,auth.uid()));
create policy members_read on public.conversation_members for select to authenticated using(public.can_chat(conversation_id,auth.uid()));
create policy messages_read on public.messages for select to authenticated using(public.can_chat(conversation_id,auth.uid()));
create policy reactions_read on public.message_reactions for select to authenticated using(exists(select 1 from public.messages where id=message_id));
create policy blocks_read on public.blocks for select to authenticated using(user_id=auth.uid());

revoke all on all functions in schema public from public,anon,authenticated;
-- RLS helpers expose only a boolean. Non-member actor probing is prevented.
create function public.member_chat_access(c uuid) returns boolean language sql stable security definer set search_path=public,pg_temp as $$select public.can_chat(c,auth.uid())$$;
-- Policies must be able to call their boolean helper, never private profile projection.
grant execute on function public.is_blocked(uuid,uuid),public.can_chat(uuid,uuid) to authenticated;
do $$ declare f record;begin for f in select p.oid::regprocedure as signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'rpc_%' loop execute format('grant execute on function %s to authenticated',f.signature);end loop;end $$;
$j1d_source$;
    insert into public.schema_migrations(name,checksum) values('202610060002_workflows.sql','afa18aa377c4477ae7905d6965ea65c5cca242ef3da2d638066a6a0082e13116');
  end if;
end
$j1d_apply$;

-- 202610060003_billing_admin.sql
do $j1d_apply$
declare previous text;
begin
  select checksum into previous from public.schema_migrations where name='202610060003_billing_admin.sql';
  if found then
    if previous <> '1b9a31b296a811a5a50150c8f4695253b76dd6cb9432ba818d848bce2e77b025' then
      raise exception 'Applied migration checksum mismatch: 202610060003_billing_admin.sql';
    end if;
  else
    execute $j1d_source$create function public.rpc_start_payment(plan uuid,operation uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(); p public.subscription_plans; result public.payments;
begin
 perform pg_advisory_xact_lock(hashtextextended(actor::text,14));
 select * into result from public.payments where user_id=actor and idempotency_key=operation;
 if found then if result.plan_id<>plan then raise exception 'IDEMPOTENCY_CONFLICT';end if;return to_jsonb(result);end if;
 select * into p from public.subscription_plans where id=plan and purchasable and amount_minor>0;
 if not found then raise exception 'PLAN_UNAVAILABLE';end if;
 if (select count(*) from public.payments where user_id=actor and created_at>now()-interval '1 hour')>=10 then raise exception 'PAYMENT_LIMIT';end if;
 insert into public.payments(user_id,plan_id,reference,idempotency_key,amount_minor,currency,period_days) values(actor,plan,'j1d_'||replace(gen_random_uuid()::text,'-',''),operation,p.amount_minor,p.currency,p.period_days) returning * into result;return to_jsonb(result);
end $$;
-- Only server privilege can execute this function. It is called after signature and provider verification.
create function public.settle_payment(ref text,amount bigint,ccy text,event_key text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare p public.payments; sub_id uuid; start_time timestamptz;
begin
 select * into p from public.payments where reference=ref for update;
 if not found or p.amount_minor<>amount or p.currency<>ccy then raise exception 'PAYMENT_MISMATCH';end if;
 if p.status='successful' then return jsonb_build_object('settled',true,'duplicate',true);end if;
 if p.status not in('initiated','pending') then raise exception 'PAYMENT_STATE_CONFLICT';end if;
 insert into public.payment_events(provider,event_key,event_type,payment_id) values('paystack',event_key,'charge.success',p.id) on conflict do nothing;
 if not found then raise exception 'PAYMENT_EVENT_CONFLICT';end if;
 perform pg_advisory_xact_lock(hashtextextended(p.user_id::text,15));
 select greatest(now(),coalesce(max(ends_at),now())) into start_time from public.subscriptions where user_id=p.user_id and status='active' and ends_at>now();
 insert into public.subscriptions(user_id,plan_id,payment_id,starts_at,ends_at) values(p.user_id,p.plan_id,p.id,start_time,start_time+make_interval(days=>p.period_days)) returning id into sub_id;
 update public.payments set status='successful',settled_at=now() where id=p.id;
 perform public.notify(p.user_id,'subscription','Your membership is confirmed',sub_id);
 insert into public.analytics_events(user_id,event) values(p.user_id,'subscription_started');
 return jsonb_build_object('settled',true,'subscription_id',sub_id);
end $$;
create function public.rpc_cancel_subscription() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor();
begin
 -- Initial billing is explicitly nonrecurring; access stays until the paid period ends.
 if exists(select 1 from public.subscriptions where user_id=actor and provider_subscription_code is not null and status='active') then raise exception 'RECURRING_CANCEL_REQUIRES_PROVIDER';end if;
 update public.subscriptions set cancel_at_period_end=true where user_id=actor and status='active' and ends_at>now();
 insert into public.analytics_events(user_id,event) values(actor,'subscription_cancelled');return '{"cancel_at_period_end":true,"renewal":"manual"}'::jsonb;
end $$;
create function public.require_admin(permission text) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(); r text;
begin select role into r from public.admin_users where user_id=actor and active;
 if r is null or not (r='SUPER_ADMIN' or (r='ADMIN' and permission in('users','moderation','verification','analytics','settings','audit')) or (r='MODERATOR' and permission in('moderation','verification')) or (r='SUPPORT' and permission='users') or (r='FINANCE' and permission='finance') or (r='ANALYST' and permission='analytics')) then raise exception 'ADMIN_FORBIDDEN';end if;return actor;end $$;
create function public.rpc_admin_identity() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor();
begin return (select jsonb_build_object('role',role,'user_id',user_id) from public.admin_users where user_id=actor and active);end $$;
create function public.rpc_admin_metrics() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
begin perform public.require_admin('analytics');return jsonb_build_object('total_users',(select count(*) from public.users where not is_test and status<>'DELETED'),'active_users',(select count(*) from public.users where not is_test and status='ACTIVE'),'new_users_7d',(select count(*) from public.users where not is_test and created_at>now()-interval '7 days'),'matches',(select count(*) from public.matches),'messages',(select count(*) from public.messages),'open_reports',(select count(*) from public.reports where status='open'),'verified_users',(select count(distinct user_id) from public.profile_verifications where method='selfie' and revoked_at is null),'active_subscriptions',(select count(*) from public.subscriptions where status='active' and starts_at<=now() and ends_at>now()),'revenue_by_currency',coalesce((select jsonb_object_agg(currency,total) from (select currency,sum(amount_minor) total from public.payments where status='successful' group by currency)x),'{}'::jsonb));end $$;
create function public.rpc_admin_queue() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
begin perform public.require_admin('moderation');return coalesce((select jsonb_agg(to_jsonb(x)) from (select q.id,q.user_id,q.kind,q.risk_score,q.signals,q.created_at,r.id report_id,r.category,r.details from public.moderation_queue q left join public.reports r on r.id=q.report_id where q.status='pending' order by q.created_at limit 100)x),'[]'::jsonb);end $$;
create function public.rpc_admin_moderate(payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_admin('moderation'); target uuid:=(payload->>'user_id')::uuid; action text:=payload->>'action'; aid uuid;
begin
 if target=actor or exists(select 1 from public.admin_users where user_id=target and active) then raise exception 'ADMIN_TARGET_RESTRICTED';end if;
 if length(payload->>'reason') not between 10 and 1000 or action not in('warn','suspend','ban','restore') then raise exception 'INVALID_ACTION';end if;
 perform 1 from public.users where id=target for update;if not found then raise exception 'USER_UNAVAILABLE';end if;
 if action='restore' then update public.users set status='PROFILE_COMPLETED',updated_at=now() where id=target and status in('SUSPENDED','BANNED');
 elsif action='suspend' then update public.users set status='SUSPENDED',updated_at=now() where id=target;
 elsif action='ban' then update public.users set status='BANNED',updated_at=now() where id=target;end if;
 insert into public.admin_actions(admin_id,action,target_id,reason) values(actor,action,target,payload->>'reason') returning id into aid;
 insert into public.audit_logs(actor_id,action,resource_id,metadata) values(actor,'admin_'||action,target,jsonb_build_object('admin_action_id',aid));
 if payload->>'report_id' is not null then update public.reports set status='resolved' where id=(payload->>'report_id')::uuid and target_id=target;update public.moderation_queue set status='resolved' where report_id=(payload->>'report_id')::uuid and user_id=target;end if;
 perform public.notify(target,'admin','Your account has a moderation update',aid);
 return jsonb_build_object('action_id',aid);
end $$;
create function public.rpc_admin_photos() returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
begin perform public.require_admin('verification');return coalesce((select jsonb_agg(to_jsonb(x)) from (select id,user_id,storage_key,created_at from public.profile_photos where moderation_status='pending' order by created_at limit 50)x),'[]'::jsonb);end $$;
create function public.rpc_admin_photo_review(photo uuid,approved boolean,reason text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_admin('verification'); target uuid; aid uuid;
begin
 if length(reason) not between 10 and 1000 then raise exception 'REASON_REQUIRED';end if;
 select user_id into target from public.profile_photos where id=photo for update;if not found then raise exception 'PHOTO_UNAVAILABLE';end if;
 if target=actor then raise exception 'SELF_REVIEW_FORBIDDEN';end if;
 update public.profile_photos set moderation_status=case when approved then 'approved' else 'rejected' end where id=photo;
 if approved then update public.users set status='ACTIVE',updated_at=now() where id=target and status in('PROFILE_COMPLETED','PHOTO_ADDED') and exists(select 1 from public.profiles where user_id=target and completion>=88) and exists(select 1 from auth.users where id=target and email_confirmed_at is not null);update public.profiles set completion=100 where user_id=target and exists(select 1 from public.users where id=target and status='ACTIVE');end if;
 insert into public.admin_actions(admin_id,action,target_id,reason) values(actor,case when approved then 'photo_approved' else 'photo_rejected' end,target,reason) returning id into aid;
 insert into public.audit_logs(actor_id,action,resource_id,metadata) values(actor,'photo_review',photo,jsonb_build_object('approved',approved,'action_id',aid));
 perform public.notify(target,'verification',case when approved then 'Your photo has been approved' else 'Your photo needs attention' end,photo);return '{"reviewed":true}'::jsonb;
end $$;
create function public.rpc_add_photo(key text,pos int,mime_value text,size int) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(); result uuid;
begin if key not like actor::text||'/%' then raise exception 'INVALID_STORAGE_KEY';end if;insert into public.profile_photos(user_id,storage_key,position,mime,size_bytes) values(actor,key,pos,mime_value,size) returning id into result;insert into public.moderation_queue(user_id,resource_id,kind) values(actor,result,'profile_photo');return jsonb_build_object('id',result,'status','pending');end $$;
create function public.rpc_contact(payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(); result uuid;
begin if length(payload->>'name') not between 2 and 100 or payload->>'phone' !~ '^\+[1-9][0-9]{7,14}$' or not (payload->>'consent_confirmed')::boolean then raise exception 'INVALID_CONTACT';end if;insert into public.emergency_contacts(user_id,name,phone,consent_confirmed) values(actor,payload->>'name',payload->>'phone',true) returning id into result;return jsonb_build_object('id',result);end $$;
create function public.rpc_notification_read(nid uuid) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor();begin update public.notifications set read_at=now() where id=nid and user_id=actor;return '{"read":true}'::jsonb;end $$;
create function public.rpc_notification_preferences(payload jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor();begin update public.notification_preferences set push_enabled=coalesce((payload->>'push_enabled')::boolean,push_enabled),email_enabled=coalesce((payload->>'email_enabled')::boolean,email_enabled),likes_enabled=coalesce((payload->>'likes_enabled')::boolean,likes_enabled),messages_enabled=coalesce((payload->>'messages_enabled')::boolean,messages_enabled),updated_at=now() where user_id=actor;return '{"saved":true}'::jsonb;end $$;
create function public.rpc_device_token(token_value text,platform_value text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor();begin if token_value !~ '^(ExponentPushToken|ExpoPushToken)\[[A-Za-z0-9_-]+\]$' then raise exception 'INVALID_PUSH_TOKEN';end if;insert into public.device_tokens(user_id,token,platform) values(actor,token_value,platform_value) on conflict(token) do update set user_id=actor,platform=platform_value,updated_at=now();return '{"registered":true}'::jsonb;end $$;

-- Member API writes are service-only. RLS client access remains read-only.
-- The API supplies a remotely validated actor in transaction-local claims.
revoke all on all functions in schema public from public,anon,authenticated;
grant execute on all functions in schema public to service_role;
-- Boolean policy wrappers bind actor internally, avoiding caller-supplied identities.
create function public.own_chat_access(c uuid) returns boolean language sql stable security definer set search_path=public,pg_temp as $$select public.can_chat(c,auth.uid())$$;
create function public.own_match_access(m uuid) returns boolean language sql stable security definer set search_path=public,pg_temp as $$select exists(select 1 from public.matches x join public.conversations c on c.match_id=x.id where x.id=m and public.can_chat(c.id,auth.uid()))$$;
revoke all on function public.own_chat_access(uuid),public.own_match_access(uuid) from public,anon;
grant execute on function public.own_chat_access(uuid),public.own_match_access(uuid) to authenticated,service_role;
drop policy matches_read on public.matches;
create policy matches_read on public.matches for select to authenticated using(public.own_match_access(id));
drop policy conversations_read on public.conversations;
create policy conversations_read on public.conversations for select to authenticated using(public.own_chat_access(id));
drop policy members_read on public.conversation_members;
create policy members_read on public.conversation_members for select to authenticated using(public.own_chat_access(conversation_id));
drop policy messages_read on public.messages;
create policy messages_read on public.messages for select to authenticated using(public.own_chat_access(conversation_id));
$j1d_source$;
    insert into public.schema_migrations(name,checksum) values('202610060003_billing_admin.sql','1b9a31b296a811a5a50150c8f4695253b76dd6cb9432ba818d848bce2e77b025');
  end if;
end
$j1d_apply$;

-- 202610060004_storage_realtime.sql
do $j1d_apply$
declare previous text;
begin
  select checksum into previous from public.schema_migrations where name='202610060004_storage_realtime.sql';
  if found then
    if previous <> '23ebc042848c953cc72e0eeb84b16aa1c701b82965d4b6fc6fe3a9499ae7feda' then
      raise exception 'Applied migration checksum mismatch: 202610060004_storage_realtime.sql';
    end if;
  else
    execute $j1d_source$-- Supabase-managed schemas are optional only for embedded PostgreSQL tests.
-- Hosted Supabase always has storage/realtime; no public bucket is created.
do $$ begin
 if to_regclass('storage.buckets') is not null then
  insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('profile-photos','profile-photos',false,5242880,array['image/jpeg']),('verification-evidence','verification-evidence',false,5242880,array['image/jpeg']) on conflict(id) do nothing;
  -- No client INSERT/SELECT policies: server validates upload and signs only approved keys.
 end if;
 if exists(select 1 from pg_publication where pubname='supabase_realtime') then
  alter publication supabase_realtime add table public.messages,public.notifications,public.conversation_members,public.message_reactions;
 end if;
end $$;
$j1d_source$;
    insert into public.schema_migrations(name,checksum) values('202610060004_storage_realtime.sql','23ebc042848c953cc72e0eeb84b16aa1c701b82965d4b6fc6fe3a9499ae7feda');
  end if;
end
$j1d_apply$;

-- 202610060005_hardening.sql
do $j1d_apply$
declare previous text;
begin
  select checksum into previous from public.schema_migrations where name='202610060005_hardening.sql';
  if found then
    if previous <> '8a4cfb6c13cf538586dc860aad5b6d25d4847d934ae62fa5e3990ac0f5ce8342' then
      raise exception 'Applied migration checksum mismatch: 202610060005_hardening.sql';
    end if;
  else
    execute $j1d_source$-- Immutable quota usage survives unmatching. Removing a relationship must not reset daily limits.
create table public.interaction_operations(id uuid primary key, user_id uuid not null references public.users(id) on delete cascade, target_id uuid not null references public.users(id) on delete cascade, action text not null check(action in('like','super_like','pass')), charged boolean not null default false, response jsonb, created_at timestamptz not null default now());
alter table public.interaction_operations enable row level security;
revoke all on public.interaction_operations from anon,authenticated;
grant all on public.interaction_operations to service_role;
create index interaction_operations_quota_idx on public.interaction_operations(user_id,created_at) where charged;
create index interaction_operations_target_idx on public.interaction_operations(target_id);

-- Preserve the tested matching transaction and wrap it with durable operation identity.
alter function public.rpc_interact(uuid,uuid,text) rename to interact_transaction;
create function public.rpc_interact(target uuid,operation uuid,action text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(true); previous public.interaction_operations; result jsonb; quota int; used int; charge boolean; existing_match uuid; existing_conversation uuid;
begin
 if target=actor or action not in('like','super_like','pass') then raise exception 'INVALID_INTERACTION';end if;
 perform pg_advisory_xact_lock(hashtextextended(actor::text,11));
 perform pg_advisory_xact_lock(hashtextextended(least(actor,target)::text||greatest(actor,target)::text,12));
 if not public.eligible_pair(actor,target) then raise exception 'PROFILE_UNAVAILABLE';end if;
 select * into previous from public.interaction_operations where id=operation;
 if found then
  if previous.user_id<>actor or previous.target_id<>target or previous.action<>action then raise exception 'IDEMPOTENCY_CONFLICT';end if;
  if action='pass' then return previous.response;end if;
  select m.id,c.id into existing_match,existing_conversation from public.matches m join public.conversations c on c.match_id=m.id where m.user_a=least(actor,target) and m.user_b=greatest(actor,target) and m.ended_at is null;
  return jsonb_build_object('matched',existing_match is not null,'match_id',existing_match,'conversation_id',existing_conversation);
 end if;
 charge:=action<>'pass' and not exists(select 1 from public.likes where user_id=actor and target_id=target);
 if charge then
  quota:=coalesce((public.entitlements(actor)->>'daily_likes')::int,0);
  select count(*) into used from public.interaction_operations where user_id=actor and charged and created_at>=date_trunc('day',now());
  if used>=quota then raise exception 'DAILY_LIMIT';end if;
  if action='super_like' then
   select count(*) into used from public.interaction_operations where user_id=actor and charged and action='super_like' and created_at>=date_trunc('day',now());
   if used>=coalesce((public.entitlements(actor)->>'super_likes')::int,0) then raise exception 'PREMIUM_REQUIRED';end if;
  end if;
 end if;
 result:=public.interact_transaction(target,operation,action);
 insert into public.interaction_operations(id,user_id,target_id,action,charged,response) values(operation,actor,target,action,charge,result);
 return result;
end $$;
revoke all on function public.rpc_interact(uuid,uuid,text),public.interact_transaction(uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.rpc_interact(uuid,uuid,text),public.interact_transaction(uuid,uuid,text) to service_role;

-- Pagination is enforced even if a client omits its cursor.
drop function public.rpc_matches();
create function public.rpc_matches(before_time timestamptz default null,before_id uuid default null) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(true);
begin return coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'conversation_id',m.cid,'created_at',m.created_at,'profile',public.profile_projection(case when m.user_a=actor then m.user_b else m.user_a end)) order by m.created_at desc,m.id desc) from (select x.*,c.id cid from public.matches x join public.conversations c on c.match_id=x.id where public.can_chat(c.id,actor) and (before_time is null or (x.created_at,x.id)<(before_time,before_id)) order by x.created_at desc,x.id desc limit 30)m),'[]'::jsonb);end $$;
revoke all on function public.rpc_matches(timestamptz,uuid) from public,anon,authenticated;
grant execute on function public.rpc_matches(timestamptz,uuid) to service_role;

-- Strictly private typing channels. Check membership against the signed-in actor.
create function public.realtime_topic_access(topic text) returns boolean language plpgsql stable security definer set search_path=public,pg_temp as $$
begin if topic !~ '^conversation:[0-9a-f-]{36}$' then return false;end if;return public.can_chat(substring(topic from 14)::uuid,auth.uid());exception when invalid_text_representation then return false;end $$;
revoke all on function public.realtime_topic_access(text) from public,anon;
grant execute on function public.realtime_topic_access(text) to authenticated,service_role;
do $$ begin if to_regclass('realtime.messages') is not null then
 create policy just1date_typing_read on realtime.messages for select to authenticated using(extension='broadcast' and public.realtime_topic_access(realtime.topic()));
 create policy just1date_typing_send on realtime.messages for insert to authenticated with check(extension='broadcast' and public.realtime_topic_access(realtime.topic()));
end if;end $$;
$j1d_source$;
    insert into public.schema_migrations(name,checksum) values('202610060005_hardening.sql','8a4cfb6c13cf538586dc860aad5b6d25d4847d934ae62fa5e3990ac0f5ce8342');
  end if;
end
$j1d_apply$;

-- 202610060006_account_access.sql
do $j1d_apply$
declare previous text;
begin
  select checksum into previous from public.schema_migrations where name='202610060006_account_access.sql';
  if found then
    if previous <> '3580026fe222413d477fba83a4d1b3564b8e94ce63b2ce8f1405b2d8d0c04bf5' then
      raise exception 'Applied migration checksum mismatch: 202610060006_account_access.sql';
    end if;
  else
    execute $j1d_source$-- Old JWTs may remain cryptographically valid until expiry after logout/deletion.
-- This account-state predicate also revokes direct Supabase private-row reads.
create function public.own_account_available() returns boolean language sql stable security definer set search_path=public,pg_temp as $$select exists(select 1 from public.users where id=auth.uid() and status not in('SUSPENDED','BANNED','DEACTIVATED','DELETION_PENDING','DELETED'))$$;
revoke all on function public.own_account_available() from public,anon;
grant execute on function public.own_account_available() to authenticated,service_role;
do $$ declare t text;begin
 foreach t in array array['users','profiles','user_preferences','user_locations','profile_photos','profile_prompts','profile_interests','education','employment','lifestyle_preferences','likes','passes','super_likes','match_preferences','reports','notifications','notification_preferences','device_tokens','subscriptions','payments','verification_requests','profile_verifications','emergency_contacts','date_plans','date_safety_sessions','compatibility_scores','ai_recommendations','profile_views','user_boosts','account_deletion_requests'] loop
  execute format('drop policy own_read on public.%I',t);
  execute format('create policy own_read on public.%I for select to authenticated using (%I=(select auth.uid()) and (select public.own_account_available()))',t,case when t='users' then 'id' else 'user_id' end);
 end loop;
end $$;
-- Rejected photos can no longer leave an account discoverable without approved imagery.
create function public.sync_photo_activation() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin if old.moderation_status='approved' and new.moderation_status<>'approved' and not exists(select 1 from public.profile_photos where user_id=new.user_id and moderation_status='approved') then update public.users set status='PROFILE_COMPLETED' where id=new.user_id and status='ACTIVE';update public.profiles set completion=88 where user_id=new.user_id;end if;return new;end $$;
create trigger sync_photo_activation after update of moderation_status on public.profile_photos for each row execute function public.sync_photo_activation();
revoke all on function public.sync_photo_activation() from public,anon,authenticated;
grant execute on function public.sync_photo_activation() to service_role;
$j1d_source$;
    insert into public.schema_migrations(name,checksum) values('202610060006_account_access.sql','3580026fe222413d477fba83a4d1b3564b8e94ce63b2ce8f1405b2d8d0c04bf5');
  end if;
end
$j1d_apply$;

-- 202610070007_inbox.sql
do $j1d_apply$
declare previous text;
begin
  select checksum into previous from public.schema_migrations where name='202610070007_inbox.sql';
  if found then
    if previous <> 'b7b4b98021919f4da9632802e5b52dd417a533b293f57414dd18e5ed42e56878' then
      raise exception 'Applied migration checksum mismatch: 202610070007_inbox.sql';
    end if;
  else
    execute $j1d_source$-- Read-only inbox metadata. Caller identity and blocked/ended relationships are
-- checked by rpc_matches/can_chat. No presence is inferred from activity times.
create function public.rpc_inbox(before_time timestamptz default null,before_id uuid default null)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare actor uuid:=public.require_actor(true); result jsonb;
begin
  select coalesce(jsonb_agg(item || jsonb_build_object(
    'last_message', (select jsonb_build_object('body', case when x.deleted_at is null then left(x.body,120) else null end,'created_at',x.created_at,'sender_id',x.sender_id,'deleted',x.deleted_at is not null) from public.messages x where x.conversation_id=(item->>'conversation_id')::uuid order by x.created_at desc,x.id desc limit 1),
    'unread_count', (select count(*) from public.messages x join public.conversation_members cm on cm.conversation_id=x.conversation_id and cm.user_id=actor where x.conversation_id=(item->>'conversation_id')::uuid and x.sender_id<>actor and x.deleted_at is null and x.created_at>coalesce(cm.last_read_at,'-infinity'::timestamptz))
  ) order by (item->>'created_at')::timestamptz desc,(item->>'id')::uuid desc),'[]'::jsonb) into result
  from jsonb_array_elements(public.rpc_matches(before_time,before_id)) item;
  return result;
end $$;
revoke all on function public.rpc_inbox(timestamptz,uuid) from public,anon,authenticated;
grant execute on function public.rpc_inbox(timestamptz,uuid) to service_role;
create index if not exists messages_unread_idx on public.messages(conversation_id,created_at) where deleted_at is null;

-- Real, configurable catalog options represented in the supplied design.
insert into public.interests(code,name) values
('shopping','Shopping'),('karaoke','Karaoke'),('yoga','Yoga'),('tennis','Tennis'),
('running','Run'),('swimming','Swimming'),('extreme','Extreme sports'),('gaming','Video games')
on conflict(code) do nothing;
$j1d_source$;
    insert into public.schema_migrations(name,checksum) values('202610070007_inbox.sql','b7b4b98021919f4da9632802e5b52dd417a533b293f57414dd18e5ed42e56878');
  end if;
end
$j1d_apply$;

-- 202610070008_deployment_security.sql
do $j1d_apply$
declare previous text;
begin
  select checksum into previous from public.schema_migrations where name='202610070008_deployment_security.sql';
  if found then
    if previous <> 'f145e52b7541129d601435769747b3f3b3b728932048d2b595af041c59cfe0f6' then
      raise exception 'Applied migration checksum mismatch: 202610070008_deployment_security.sql';
    end if;
  else
    execute $j1d_source$-- The custom migration ledger is infrastructure, never a client-readable catalog.
create table if not exists public.schema_migrations (
  name text primary key,
  checksum text not null,
  applied_at timestamptz not null default now()
);
alter table public.schema_migrations enable row level security;
revoke all on public.schema_migrations from public, anon, authenticated;
grant all on public.schema_migrations to service_role;

-- If buckets already existed, make their configuration match the upload contract.
do $$ begin
  if to_regclass('storage.buckets') is not null then
    update storage.buckets set public=false, file_size_limit=5242880,
      allowed_mime_types=array['image/jpeg']
    where id in ('profile-photos','verification-evidence');
  end if;
end $$;
$j1d_source$;
    insert into public.schema_migrations(name,checksum) values('202610070008_deployment_security.sql','f145e52b7541129d601435769747b3f3b3b728932048d2b595af041c59cfe0f6');
  end if;
end
$j1d_apply$;

-- 202610070009_rate_limits.sql
do $j1d_apply$
declare previous text;
begin
  select checksum into previous from public.schema_migrations where name='202610070009_rate_limits.sql';
  if found then
    if previous <> '682ed5a0cf2f1a935e7b965b8dbd66ded3e9aa32268db6c957e140d458cf871a' then
      raise exception 'Applied migration checksum mismatch: 202610070009_rate_limits.sql';
    end if;
  else
    execute $j1d_source$-- Shared counters survive serverless instance changes. No Redis service is required.
-- Keys are HMAC digests; raw client IP addresses are not stored here.
create table public.request_rate_limits (
 namespace text not null check(namespace in ('api','auth')),
 key text not null check(length(key)=64),
 total_hits bigint not null check(total_hits>=0),
 reset_at timestamptz not null,
 primary key(namespace,key)
);
create index request_rate_limits_expiry_idx on public.request_rate_limits(reset_at);
alter table public.request_rate_limits enable row level security;
revoke all on public.request_rate_limits from public,anon,authenticated;
grant all on public.request_rate_limits to service_role;
$j1d_source$;
    insert into public.schema_migrations(name,checksum) values('202610070009_rate_limits.sql','682ed5a0cf2f1a935e7b965b8dbd66ded3e9aa32268db6c957e140d458cf871a');
  end if;
end
$j1d_apply$;

-- 202610080010_demo.sql
do $j1d_apply$
declare previous text;
begin
  select checksum into previous from public.schema_migrations where name='202610080010_demo.sql';
  if found then
    if previous <> 'e98ed146ab7f4115802f67869b56b9dd9642c6899b103adaf35298fd671e9ee0' then
      raise exception 'Applied migration checksum mismatch: 202610080010_demo.sql';
    end if;
  else
    execute $j1d_source$-- Exactly four fictional profiles. No Auth accounts or production member records.
create table public.demo_profiles (
  slot smallint primary key check (slot between 1 and 4),
  id uuid not null unique,
  name text not null, age smallint not null check (age >= 18),
  gender text not null check (gender in ('woman','man')),
  city text not null, profession text not null, bio text not null,
  interests text[] not null, values_list text[] not null,
  prompt text not null, answer text not null, image text not null,
  sample_reply text not null, removed_at timestamptz
);
create table public.demo_sessions (
  id uuid primary key,
  expires_at timestamptz not null,
  state jsonb not null default '{"likes":[],"passes":[],"messages":{},"gender":"everyone"}'::jsonb,
  check (octet_length(state::text) < 524288)
);
create index demo_sessions_expiry on public.demo_sessions(expires_at);
alter table public.demo_profiles enable row level security;
alter table public.demo_sessions enable row level security;
revoke all on public.demo_profiles,public.demo_sessions from public,anon,authenticated;
grant all on public.demo_profiles,public.demo_sessions to service_role;
insert into public.demo_profiles(slot,id,name,age,gender,city,profession,bio,interests,values_list,prompt,answer,image,sample_reply) values
(1,'d1111111-1111-4111-8111-111111111111','Amara',28,'woman','Lagos','Product designer','A good conversation, an undiscovered bookshop, and a little spontaneity. I’m looking for someone kind who is ready to build something meaningful.',array['Art & design','Coffee','Travel'],array['Kindness','Curiosity','Honesty'],'My perfect Sunday','A slow morning, a gallery visit, and dinner with the people I love.','/images/demo/amara.png','A bookshop and coffee would be my ideal first date. What does your perfect Sunday look like?'),
(2,'d2222222-2222-4222-8222-222222222222','Tomi',31,'man','Abuja','Architect','Usually sketching a building, planning a weekend escape, or cooking something ambitious. Looking for a thoughtful connection with room for laughter.',array['Architecture','Cooking','Hiking'],array['Family','Creativity','Consistency'],'The way to my heart','Remember the little things. And let me cook you my favourite meal.','/images/demo/tomi.png','I’d choose a relaxed dinner and a good conversation. What’s a meal you could eat every week?'),
(3,'d3333333-3333-4333-8333-333333333333','Zara',27,'woman','Lagos','Creative strategist','Live music, seaside walks, and conversations that go somewhere. A little adventurous, a lot intentional. Let’s find a new favourite place together.',array['Live music','Photography','Beach walks'],array['Growth','Empathy','Adventure'],'We’ll get along if','You can laugh at yourself and you’re curious about the world.','/images/demo/zara.png','A seaside walk and live music sounds lovely. Which artist is on your playlist right now?'),
(4,'d4444444-4444-4444-8444-444444444444','Daniel',30,'man','Port Harcourt','Software engineer','A reader, a runner, and the friend who plans the trip. I value clear communication and showing up. Here for a relationship with depth and a sense of humour.',array['Reading','Running','Travel'],array['Honesty','Ambition','Balance'],'A small thing that matters','Making time for each other, even on the busiest days.','/images/demo/daniel.png','My ideal first date is a quiet cafe where we can really talk. What’s the best book you’ve read recently?');
$j1d_source$;
    insert into public.schema_migrations(name,checksum) values('202610080010_demo.sql','e98ed146ab7f4115802f67869b56b9dd9642c6899b103adaf35298fd671e9ee0');
  end if;
end
$j1d_apply$;

commit;
