-- Initial schema. Apply transactionally using the migration runner.
create type public.account_status as enum ('REGISTERED','EMAIL_VERIFIED','PROFILE_STARTED','PROFILE_COMPLETED','PHOTO_ADDED','VERIFICATION_PENDING','VERIFIED','ACTIVE','SUSPENDED','BANNED','DEACTIVATED','DELETION_PENDING','DELETED');
create table public.app_settings(id uuid primary key default gen_random_uuid(), key text unique not null, value jsonb not null, updated_at timestamptz not null default now());
create table public.feature_flags(id uuid primary key default gen_random_uuid(), key text unique not null, enabled boolean not null default false, rollout_percent int not null default 0 check(rollout_percent between 0 and 100), updated_at timestamptz not null default now());
create table public.users(id uuid primary key references auth.users(id) on delete cascade, date_of_birth date not null check(date_of_birth > date '1900-01-01'), status public.account_status not null default 'REGISTERED', is_test boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.relationship_goals(id uuid primary key default gen_random_uuid(), code text unique not null, name text not null);
create table public.interests(id uuid primary key default gen_random_uuid(), code text unique not null, name text not null, active boolean not null default true);
create table public.profiles(user_id uuid primary key references public.users(id) on delete cascade, display_name text not null default '', gender text not null default '' check(gender in ('','woman','man','nonbinary','self_described')), city text not null default '', bio text not null default '' check(length(bio)<=1000), profession text not null default '', education text not null default '', goal text references public.relationship_goals(code), values text[] not null default '{}', communication text not null default '', personality text[] not null default '{}', visible boolean not null default true, paused boolean not null default false, show_online boolean not null default false, completion int not null default 0 check(completion between 0 and 100), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_preferences(user_id uuid primary key references public.users(id) on delete cascade, age_min int not null default 18 check(age_min>=18), age_max int not null default 60 check(age_max<=100), genders text[] not null default '{woman,man,nonbinary,self_described}', goals text[] not null default '{}', distance_km int not null default 100 check(distance_km between 1 and 500), deal_breakers jsonb not null default '{}', updated_at timestamptz not null default now(), check(age_min<=age_max));
create table public.user_locations(user_id uuid primary key references public.users(id) on delete cascade, latitude numeric(5,2) check(latitude between -90 and 90), longitude numeric(5,2) check(longitude between -180 and 180), city text not null, consent_at timestamptz, updated_at timestamptz not null default now(), check((latitude is null)=(longitude is null)));
create table public.profile_photos(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, storage_key text unique not null, position int not null check(position between 0 and 5), moderation_status text not null default 'pending' check(moderation_status in ('pending','approved','rejected')), mime text not null check(mime in ('image/jpeg','image/png','image/webp')), size_bytes int not null check(size_bytes between 1 and 5242880), created_at timestamptz not null default now(), unique(user_id,position));
create table public.profile_prompts(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, question text not null check(length(question) between 5 and 150), answer text not null check(length(answer) between 5 and 500), position int not null check(position between 0 and 2), unique(user_id,position));
create table public.profile_interests(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, interest_id uuid not null references public.interests(id), unique(user_id,interest_id));
create table public.education(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, institution text not null, qualification text, visible boolean not null default true, created_at timestamptz not null default now());
create table public.employment(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, profession text not null, company text, visible boolean not null default true, created_at timestamptz not null default now());
create table public.lifestyle_preferences(user_id uuid primary key references public.users(id) on delete cascade, preferences jsonb not null default '{}', updated_at timestamptz not null default now());
create table public.likes(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, target_id uuid not null references public.users(id) on delete cascade, kind text not null default 'like' check(kind in ('like','super_like')), operation_id uuid unique not null, created_at timestamptz not null default now(), unique(user_id,target_id), check(user_id<>target_id));
create table public.passes(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, target_id uuid not null references public.users(id) on delete cascade, operation_id uuid unique not null, created_at timestamptz not null default now(), unique(user_id,target_id), check(user_id<>target_id));
create table public.super_likes(id uuid primary key default gen_random_uuid(), like_id uuid unique not null references public.likes(id) on delete cascade, user_id uuid not null references public.users(id) on delete cascade, created_at timestamptz not null default now());
create table public.matches(id uuid primary key default gen_random_uuid(), user_a uuid not null references public.users(id) on delete cascade, user_b uuid not null references public.users(id) on delete cascade, created_at timestamptz not null default now(), ended_at timestamptz, unique(user_a,user_b), check(user_a<user_b));
create table public.match_preferences(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, match_id uuid not null references public.matches(id) on delete cascade, muted boolean not null default false, unique(user_id,match_id));
create table public.conversations(id uuid primary key default gen_random_uuid(), match_id uuid unique not null references public.matches(id) on delete cascade, created_at timestamptz not null default now());
create table public.conversation_members(id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.conversations(id) on delete cascade, user_id uuid not null references public.users(id) on delete cascade, last_read_at timestamptz, unique(conversation_id,user_id));
create table public.messages(id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.conversations(id) on delete cascade, sender_id uuid not null references public.users(id) on delete cascade, body text check(length(body) between 1 and 2000), kind text not null default 'text' check(kind in ('text','image','voice','gif')), media_key text, reply_to uuid references public.messages(id) on delete set null, client_id uuid not null, created_at timestamptz not null default now(), deleted_at timestamptz, unique(sender_id,client_id), check(body is not null or deleted_at is not null or media_key is not null));
create table public.message_reactions(id uuid primary key default gen_random_uuid(), message_id uuid not null references public.messages(id) on delete cascade, user_id uuid not null references public.users(id) on delete cascade, emoji text not null check(length(emoji)<=16), created_at timestamptz not null default now(), unique(message_id,user_id));
create table public.blocks(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, target_id uuid not null references public.users(id) on delete cascade, created_at timestamptz not null default now(), unique(user_id,target_id), check(user_id<>target_id));
create table public.reports(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, target_id uuid not null references public.users(id) on delete cascade, category text not null check(category in ('fake_profile','scam','harassment','threats','hate','sexual_misconduct','underage','spam','other')), details text not null check(length(details) between 10 and 2000), status text not null default 'open' check(status in ('open','reviewing','resolved','dismissed')), created_at timestamptz not null default now(), check(user_id<>target_id));
create table public.message_reports(id uuid primary key default gen_random_uuid(), report_id uuid unique not null references public.reports(id) on delete cascade, message_id uuid not null references public.messages(id) on delete cascade);
create table public.notifications(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, kind text not null, title text not null, resource_id uuid, read_at timestamptz, created_at timestamptz not null default now());
create table public.notification_preferences(user_id uuid primary key references public.users(id) on delete cascade, push_enabled boolean not null default false, email_enabled boolean not null default false, likes_enabled boolean not null default true, messages_enabled boolean not null default true, updated_at timestamptz not null default now());
create table public.device_tokens(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, token text unique not null, platform text not null check(platform in ('ios','android')), updated_at timestamptz not null default now());
create table public.notification_outbox(id uuid primary key default gen_random_uuid(), notification_id uuid unique not null references public.notifications(id) on delete cascade, attempts int not null default 0, available_at timestamptz not null default now(), locked_at timestamptz, delivered_at timestamptz, last_error_code text);
create table public.subscription_plans(id uuid primary key default gen_random_uuid(), code text unique not null check(code in ('free','plus','premium')), name text not null, amount_minor bigint not null check(amount_minor>=0), currency text not null check(currency ~ '^[A-Z]{3}$'), period_days int not null check(period_days between 1 and 366), entitlements jsonb not null default '{}', purchasable boolean not null default false, provider_plan_code text, updated_at timestamptz not null default now());
create table public.payments(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id), plan_id uuid not null references public.subscription_plans(id), provider text not null default 'paystack', reference text unique not null, idempotency_key uuid not null, amount_minor bigint not null check(amount_minor>0), currency text not null, period_days int not null check(period_days>0), status text not null default 'initiated' check(status in ('initiated','pending','successful','failed','refunded')), checkout_url text, created_at timestamptz not null default now(), settled_at timestamptz, unique(user_id,idempotency_key));
create table public.subscriptions(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id), plan_id uuid not null references public.subscription_plans(id), payment_id uuid unique references public.payments(id), status text not null default 'active' check(status in ('active','expired','cancelled')), starts_at timestamptz not null, ends_at timestamptz not null, cancel_at_period_end boolean not null default false, provider_subscription_code text, created_at timestamptz not null default now(), check(ends_at>starts_at));
create table public.payment_events(id uuid primary key default gen_random_uuid(), provider text not null, event_key text not null, event_type text not null, payment_id uuid references public.payments(id), created_at timestamptz not null default now(), unique(provider,event_key));
create table public.verification_requests(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, method text not null check(method in ('selfie','photo','phone')), status text not null default 'pending' check(status in ('pending','approved','rejected')), created_at timestamptz not null default now(), reviewed_at timestamptz);
create table public.verification_results(id uuid primary key default gen_random_uuid(), request_id uuid unique not null references public.verification_requests(id) on delete cascade, result text not null, reviewer_id uuid references public.users(id), created_at timestamptz not null default now());
create table public.verification_documents(id uuid primary key default gen_random_uuid(), request_id uuid not null references public.verification_requests(id) on delete cascade, storage_key text unique not null, purge_at timestamptz not null, created_at timestamptz not null default now());
create table public.profile_verifications(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, method text not null check(method in ('email','phone','selfie','photo')), request_id uuid references public.verification_requests(id) on delete set null, verified_at timestamptz not null default now(), revoked_at timestamptz, unique(user_id,method));
create table public.emergency_contacts(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, name text not null, phone text not null, consent_confirmed boolean not null default false, created_at timestamptz not null default now());
create table public.date_plans(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, match_id uuid references public.matches(id) on delete set null, venue text not null, starts_at timestamptz not null, created_at timestamptz not null default now());
create table public.date_safety_sessions(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, person_name text not null, venue text not null, starts_at timestamptz not null, ends_at timestamptz not null, trusted_contact_id uuid references public.emergency_contacts(id) on delete set null, location_consent boolean not null default false, status text not null default 'scheduled' check(status in ('scheduled','active','ended','alert')), last_check_in_at timestamptz, ended_at timestamptz, created_at timestamptz not null default now(), check(ends_at>starts_at));
create table public.compatibility_factors(id uuid primary key default gen_random_uuid(), code text unique not null, weight numeric not null check(weight>=0), enabled boolean not null default true, updated_at timestamptz not null default now());
create table public.compatibility_scores(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, target_id uuid not null references public.users(id) on delete cascade, score numeric check(score between 0 and 100), factors jsonb not null, algorithm_version text not null, expires_at timestamptz not null, unique(user_id,target_id,algorithm_version));
create table public.ai_recommendations(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, kind text not null, output jsonb not null, model text not null, created_at timestamptz not null default now(), expires_at timestamptz not null);
create table public.profile_views(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, target_id uuid not null references public.users(id) on delete cascade, created_at timestamptz not null default now());
create table public.boosts(id uuid primary key default gen_random_uuid(), name text not null, duration_minutes int not null check(duration_minutes>0), exposure_multiplier numeric not null check(exposure_multiplier between 1 and 3), amount_minor bigint not null check(amount_minor>=0), currency text not null, enabled boolean not null default false);
create table public.user_boosts(id uuid primary key default gen_random_uuid(), user_id uuid not null references public.users(id) on delete cascade, boost_id uuid not null references public.boosts(id), purchase_id uuid unique references public.payments(id), boost_start timestamptz not null, boost_end timestamptz not null, impressions int not null default 0, profile_views int not null default 0, likes_received int not null default 0, matches_generated int not null default 0, check(boost_end>boost_start));
create table public.admin_users(user_id uuid primary key references public.users(id), role text not null check(role in ('SUPER_ADMIN','ADMIN','MODERATOR','SUPPORT','FINANCE','ANALYST')), active boolean not null default true, created_at timestamptz not null default now());
create table public.admin_actions(id uuid primary key default gen_random_uuid(), admin_id uuid not null references public.admin_users(user_id), action text not null, target_id uuid references public.users(id), reason text not null, created_at timestamptz not null default now());
create table public.moderation_queue(id uuid primary key default gen_random_uuid(), report_id uuid unique references public.reports(id), user_id uuid not null references public.users(id), resource_id uuid, kind text not null, risk_score int not null default 0 check(risk_score between 0 and 100), signals text[] not null default '{}', status text not null default 'pending' check(status in ('pending','reviewing','resolved')), created_at timestamptz not null default now());
create table public.moderation_actions(id uuid primary key default gen_random_uuid(), queue_id uuid references public.moderation_queue(id), admin_action_id uuid not null references public.admin_actions(id), created_at timestamptz not null default now());
create table public.audit_logs(id uuid primary key default gen_random_uuid(), actor_id uuid references public.users(id), action text not null, resource_id uuid, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.analytics_events(id uuid primary key default gen_random_uuid(), user_id uuid references public.users(id) on delete set null, event text not null, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create table public.account_deletion_requests(id uuid primary key default gen_random_uuid(), user_id uuid unique not null references public.users(id), status text not null default 'pending' check(status in ('pending','processing','completed','failed')), requested_at timestamptz not null default now(), completed_at timestamptz);

-- Enable deny-by-default RLS and remove Supabase's permissive default grants.
do $$ declare t record; begin
 for t in select tablename from pg_tables where schemaname='public' and tablename<>'schema_migrations' loop
  execute format('alter table public.%I enable row level security',t.tablename);
  execute format('revoke all on public.%I from anon, authenticated',t.tablename);
  execute format('grant all on public.%I to service_role',t.tablename);
 end loop;
end $$;
grant usage on schema public to anon,authenticated,service_role;
do $$ declare t text; begin
 foreach t in array array['users','profiles','user_preferences','user_locations','profile_photos','profile_prompts','profile_interests','education','employment','lifestyle_preferences','likes','passes','super_likes','match_preferences','reports','notifications','notification_preferences','device_tokens','subscriptions','payments','verification_requests','profile_verifications','emergency_contacts','date_plans','date_safety_sessions','compatibility_scores','ai_recommendations','profile_views','user_boosts','account_deletion_requests'] loop
  execute format('grant select on public.%I to authenticated',t);
  execute format('create policy own_read on public.%I for select to authenticated using (%I=(select auth.uid()))',t,case when t='users' then 'id' else 'user_id' end);
 end loop;
 foreach t in array array['interests','relationship_goals','subscription_plans','compatibility_factors'] loop
  execute format('grant select on public.%I to anon,authenticated',t);
  execute format('create policy catalog_read on public.%I for select to anon,authenticated using(true)',t);
 end loop;
end $$;

-- Index each foreign-key column, plus composite indexes for bounded list reads.
do $$ declare c record; begin
 for c in select distinct t.relname,a.attname from pg_constraint f join pg_class t on t.oid=f.conrelid join pg_namespace n on n.oid=t.relnamespace join pg_attribute a on a.attrelid=t.oid and a.attnum=any(f.conkey) where f.contype='f' and n.nspname='public' loop
  execute format('create index if not exists %I on public.%I(%I)',left(c.relname||'_'||c.attname||'_fk_idx',63),c.relname,c.attname);
 end loop;
end $$;
create index messages_cursor_idx on public.messages(conversation_id,created_at desc,id desc);
create index notifications_cursor_idx on public.notifications(user_id,created_at desc,id desc);
create index likes_daily_idx on public.likes(user_id,created_at);
create index profiles_discover_idx on public.profiles(city,gender,user_id) where visible and not paused;
create index users_active_idx on public.users(id) where status='ACTIVE';
create index subscriptions_entitlement_idx on public.subscriptions(user_id,ends_at desc) where status='active';
create index notification_outbox_due_idx on public.notification_outbox(available_at) where delivered_at is null;
create index moderation_pending_idx on public.moderation_queue(created_at) where status='pending';

insert into public.app_settings(key,value) values ('minimum_age','18'),('matching_version','"v1"');
insert into public.relationship_goals(code,name) values ('serious','Serious relationship'),('marriage','Marriage'),('long_term','Long-term dating'),('dating','Dating'),('friendship','Friendship'),('exploring','Still figuring it out');
insert into public.interests(code,name) values ('travel','Travel'),('reading','Reading'),('music','Music'),('art','Art'),('cooking','Cooking'),('fitness','Fitness'),('technology','Technology'),('nature','Nature'),('film','Film'),('photography','Photography'),('volunteering','Volunteering'),('food','Food'),('dance','Dance'),('entrepreneurship','Entrepreneurship');
-- No invented live prices. Operator must configure and enable paid plans.
insert into public.subscription_plans(code,name,amount_minor,currency,period_days,entitlements) values
 ('free','Free',0,'NGN',30,'{"daily_likes":15,"super_likes":0,"see_likes":false,"ai":false,"advanced_filters":false}'),
 ('plus','Plus',0,'NGN',30,'{"daily_likes":100,"super_likes":3,"see_likes":true,"ai":false,"advanced_filters":true}'),
 ('premium','Premium',0,'NGN',30,'{"daily_likes":100000,"super_likes":10,"see_likes":true,"ai":true,"advanced_filters":true}');
insert into public.compatibility_factors(code,weight) values ('goals',25),('values',15),('lifestyle',15),('interests',10),('communication',10),('personality',10),('preferences',10),('distance',5);
insert into public.feature_flags(key) values ('ai_matchmaker'),('video_calling'),('boosts'),('super_likes'),('verification'),('premium_filters'),('new_matching');

create function public.provision_user() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare dob date; minimum int;
begin
 minimum:=greatest(18,coalesce((select value::text::int from public.app_settings where key='minimum_age'),18));
 begin dob:=(new.raw_user_meta_data->>'date_of_birth')::date; exception when others then raise exception 'INVALID_DATE_OF_BIRTH'; end;
 if dob is null or dob>current_date-(minimum||' years')::interval or dob<current_date-interval '120 years' then raise exception 'AGE_REQUIREMENT'; end if;
 insert into public.users(id,date_of_birth,status) values(new.id,dob,case when new.email_confirmed_at is null then 'REGISTERED'::public.account_status else 'EMAIL_VERIFIED'::public.account_status end);
 insert into public.profiles(user_id) values(new.id);
 insert into public.user_preferences(user_id) values(new.id);
 insert into public.lifestyle_preferences(user_id) values(new.id);
 insert into public.notification_preferences(user_id) values(new.id);
 return new;
end $$;
create trigger provision_user after insert on auth.users for each row execute function public.provision_user();
create function public.sync_email_verification() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
begin
 if new.email_confirmed_at is not null and old.email_confirmed_at is null then
  update public.users set status='EMAIL_VERIFIED',updated_at=now() where id=new.id and status='REGISTERED';
  insert into public.profile_verifications(user_id,method) values(new.id,'email') on conflict do nothing;
 end if;
 return new;
end $$;
create trigger sync_email_verification after update of email_confirmed_at on auth.users for each row execute function public.sync_email_verification();
revoke all on all functions in schema public from public,anon,authenticated;
